### ISSUE TITLE
スマホ対応

### ISSUE THREAD

**Issue by Mow17** [winc1980/secure.register.winc.ne.jp#30]
- スマホだとpdfとGoogle Formのサイズが若干ずれるのでスマホから見ても違和感が無いように修正する

**Comment by kanako0424** [comment]
pdfとgoogle formは解決したけど、入会フローの説明ではみ出ているので、そこをやった人に解決してもらいたいです。デベロッパーツールでiphone SEに設定して確認してね。

**Comment by kanako0424** [comment]
@pontabi
