### ISSUE TITLE
フローの説明からそのフローにリンクで飛べるようにする

### ISSUE THREAD

**Issue by kanako0424** [winc1980/secure.register.winc.ne.jp#41]
1. `<h3>会則を確認する<h3>` に idタグをつける
2. 「01 会則を確認する」 をaタグで囲い、href属性を同じid名にする

**Comment by kanako0424** [comment]
ごめんね、深夜にissueだけ作って説明ちゃんとしてなかったし、後で補足しようと思っていたのだけど、まさか深夜に見てくれてそしてすぐにやってくれるとは思ってなかった。
assignだけして3/14にやってもらおうと思ってた。assignしたらもしかして通知がいくの？それだったら深夜に通知送ってごめん！！

やってほしいこと、大きくはあっていてありがたい！
細か〜く指定するとこうなります...↓

1. #40 と #35 の pull requestが承認されたら全てのフローの題名に、`<h3>フローの名前<h3>`のように、要素ができます。
例えば、「会則の確認」も今はないですが、`<h3>会則の確認</h3>` のようになります。
2. 全てのフローの題名(全ての<h3>タグ)に対して固有のid名を付けてください(例: flow1, flow2...)。id名は同じファイルの中で1つしか使えません。
3. フローの説明にある<li>要素を<a>タグで囲ってください。<a>タグはブロック要素の親要素にすることができます。<li>タグ全体を囲うことによって要素全体（文字だけではなくその背景も）をクリックすることができるようになります
5. aタグのtext-decorationに関しては、bootstrap のtext-decoration-noneクラスを使用してください。（cssは、bootstrapにあったらそれを、なかったら<style>タグ内に書いてください。）
6. 5と同じ理由で、html要素にstyle属性でcssを書くのではなく、<style>タグの中に書いてください。
7. <a>タグのhref属性は `href="#idname"`(idnameには任意のid名が入ります)にしてください（pull reqしてくれているのは`href="index.html#idname"`になっているけどindex.htmlはなくてもpathが通るよ）

そんなの知らねーよ！と思うくらい全然伝えるべきこと伝えてなかったので本当に申し訳ないです。

**Comment by Yuma769** [comment]
なるほど、`<h3>会則を確認する<h3>`ってどこにあるんだ？ってなって、とりあえずこんな感じかなってやってました笑。
14日部室行くと思うので、その時またやります！

**Comment by kanako0424** [comment]
ありがとう！14日やろう〜

疑問に思ったら深夜でもなんでも気軽に聞いてね〜
自分のタイミングで通知見るし、連投とか遠慮せずなんでも聞いてね〜

**Comment by kanako0424** [comment]
フローの数字が整ったので、#40 の説明を見ながら、issueの解決をお願いします。
