### ISSUE TITLE
04 振込の説明を表形式にして見やすくする

### ISSUE THREAD

**Issue by manasan-iTL** [winc1980/secure.register.winc.ne.jp#49]
現状の問題
・振込金額や備考の情報が黒一色の文で見づらい。
・金額の情報がぱっと見でわかりづらい

変更
・振込金額のところは表形式（03振込先情報の表形式と同様）にして文字と区別する
・備考の情報は変更しない。

**Comment by kanako0424** [comment]
「振込金額を表形式にする」と言うことらしいです。

入会費 1,000
年会費 2,000
合計     3,000

と言う表にする
