### ISSUE TITLE
よくあるお問合せが一番下にあってわかりづらいけど、どこにおくのが理想だと思う？

### ISSUE THREAD

**Issue by kanako0424** [winc1980/secure.register.winc.ne.jp#60]
よくあるお問合せが一番下にあってわかりづらいけど、どこにおくのが理想だと思う？
フローの中に組み込んで、リンクにするべき？
それともフローの前に置くべき？
それとも一番下に置いて、よくあるお問合せはこちら、っていうリンクを作るべき？
私は3つ目の方法が一番いいと思うのだけど、他の人はどう思いますか？

**Comment by manasan-iTL** [comment]
3番目の方法が良いと思います。
理由
・よくあるお問い合わせは入会ないし体験入会の際に絶対に必要なものではない。入会フローの方が重要であるので、重要な方を先に表示（前に置くこと）した方が良いと思われる
・同様によくあるお問い合わせは直接入会手続きに関係しないのでフローの中に入れるのも違和感がありそう

**Comment by kanako0424** [comment]
ありがとう！納得の理由3つとも。
2022年3月18日(金) 18:01 manasan-iTL ***@***.***>:
